/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kantor;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 *
 * @author maciejszczypta
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jTBmain = new javax.swing.JTabbedPane();
        jPbuy = new javax.swing.JPanel();
        jLmainBuy = new javax.swing.JLabel();
        jLamountBuy = new javax.swing.JLabel();
        jTFamountBuy = new javax.swing.JTextField();
        jLgetBuy = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLwhatBuy = new javax.swing.JLabel();
        jBcheckBuy = new javax.swing.JButton();
        jPsell = new javax.swing.JPanel();
        jLgetSell = new javax.swing.JLabel();
        jLmain = new javax.swing.JLabel();
        jTFamountSell = new javax.swing.JTextField();
        jLwhatSell = new javax.swing.JLabel();
        jLamountSell = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jBcheckSell = new javax.swing.JButton();
        jPcheck = new javax.swing.JPanel();
        jLmainCheck = new javax.swing.JLabel();
        jLwhatCheck = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLactionCheck = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jBcheckCheck = new javax.swing.JButton();
        jLcheckPrices = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLmainBuy.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLmainBuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmainBuy.setText("KALKULATOR WALUT");

        jLamountBuy.setText("Podaj ilość jaką chcesz kupić:");

        jLgetBuy.setText("Tyle dostaniesz:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHF", "JPY" }));

        jLwhatBuy.setText("Wybierz co chcesz kupić:");

        jBcheckBuy.setText("SPRAWDŹ");
        jBcheckBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcheckBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbuyLayout = new javax.swing.GroupLayout(jPbuy);
        jPbuy.setLayout(jPbuyLayout);
        jPbuyLayout.setHorizontalGroup(
            jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLmainBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLgetBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcheckBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuyLayout.createSequentialGroup()
                        .addGroup(jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFamountBuy)
                            .addComponent(jLamountBuy, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLwhatBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPbuyLayout.setVerticalGroup(
            jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuyLayout.createSequentialGroup()
                .addComponent(jLmainBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamountBuy)
                    .addComponent(jLwhatBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPbuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFamountBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLgetBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcheckBuy, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTBmain.addTab("KUPNO", jPbuy);

        jLgetSell.setText("Tyle dostaniesz:");

        jLmain.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLmain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmain.setText("KALKULATOR WALUT");

        jLwhatSell.setText("Wybierz co chcesz sprzedać:");

        jLamountSell.setText("Podaj ilość jaką chcesz sprzedać:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHF", "JPY" }));

        jBcheckSell.setText("SPRAWDŹ");
        jBcheckSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcheckSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPsellLayout = new javax.swing.GroupLayout(jPsell);
        jPsell.setLayout(jPsellLayout);
        jPsellLayout.setHorizontalGroup(
            jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLgetSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcheckSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsellLayout.createSequentialGroup()
                        .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFamountSell)
                            .addComponent(jLamountSell, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLwhatSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPsellLayout.setVerticalGroup(
            jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellLayout.createSequentialGroup()
                .addComponent(jLmain, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamountSell)
                    .addComponent(jLwhatSell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFamountSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLgetSell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcheckSell, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTBmain.addTab("SPRZEDAŻ", jPsell);

        jLmainCheck.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLmainCheck.setText("SPRAWDŹ NAJWIĘKSZA I NAJMNIEJSZĄ CENE Z HISTORI:");

        jLwhatCheck.setText("Wybierz walute jaką chcesz sprawdzić:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHF", "JPY" }));

        jLactionCheck.setText("Wybierz co chcesz sprawdzić:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUY", "SELL" }));

        jBcheckCheck.setText("SPRAWDŹ");
        jBcheckCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcheckCheckActionPerformed(evt);
            }
        });

        jLcheckPrices.setText("Najmniejsza/Największa:");

        javax.swing.GroupLayout jPcheckLayout = new javax.swing.GroupLayout(jPcheck);
        jPcheck.setLayout(jPcheckLayout);
        jPcheckLayout.setHorizontalGroup(
            jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcheckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcheckPrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcheckCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLmainCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPcheckLayout.createSequentialGroup()
                        .addGroup(jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLactionCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLwhatCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPcheckLayout.setVerticalGroup(
            jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcheckLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLmainCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLwhatCheck)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLactionCheck)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLcheckPrices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jBcheckCheck)
                .addContainerGap())
        );

        jTBmain.addTab("SPRAWDŹ DANE", jPcheck);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTBmain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTBmain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcheckBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcheckBuyActionPerformed
        try{
            BigDecimal amount = new BigDecimal(jTFamountBuy.getText());
            GetPriceFromAPI api = new GetPriceFromAPI();
            SaveDataToFile saver = new SaveDataToFile();
            String currency = jComboBox1.getSelectedItem().toString();
            BigDecimal price = api.getPrice("buy", currency);
            
            System.out.print(price);
            
            BigDecimal res = amount.divide(price, 2, RoundingMode.HALF_UP);
            jLgetBuy.setText("Tyle otrzymasz: "+res);
            saver.saveData("buy", currency, amount, res, price);
        }catch(Exception e){
            System.out.println("err");
        }
        
        
    }//GEN-LAST:event_jBcheckBuyActionPerformed

    private void jBcheckSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcheckSellActionPerformed
        try{
            BigDecimal amount = new BigDecimal(jTFamountSell.getText());
            //double amount = Double.parseDouble(jTFamountSell.getText());
            GetPriceFromAPI api = new GetPriceFromAPI();
            SaveDataToFile saver = new SaveDataToFile();
            String currency = jComboBox2.getSelectedItem().toString();
            
            BigDecimal price = api.getPrice("sell", currency);
            BigDecimal res = amount.multiply(price).setScale(2, RoundingMode.UP);
            
            jLgetSell.setText("Tyle otrzymasz: "+res);
            saver.saveData("sell", currency, amount, res, price); 
        }catch(Exception e){
            System.out.println("err");
        }
        
    }//GEN-LAST:event_jBcheckSellActionPerformed

    private void jBcheckCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcheckCheckActionPerformed
        ReadDataFromFile reader = new ReadDataFromFile();
        String currency = jComboBox3.getSelectedItem().toString();
        String action = jComboBox4.getSelectedItem().toString();
        jLcheckPrices.setText("Najmniejsza/Największa:"+reader.readData(action.toLowerCase(), currency));
    }//GEN-LAST:event_jBcheckCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcheckBuy;
    private javax.swing.JButton jBcheckCheck;
    private javax.swing.JButton jBcheckSell;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLactionCheck;
    private javax.swing.JLabel jLamountBuy;
    private javax.swing.JLabel jLamountSell;
    private javax.swing.JLabel jLcheckPrices;
    private javax.swing.JLabel jLgetBuy;
    private javax.swing.JLabel jLgetSell;
    private javax.swing.JLabel jLmain;
    private javax.swing.JLabel jLmainBuy;
    private javax.swing.JLabel jLmainCheck;
    private javax.swing.JLabel jLwhatBuy;
    private javax.swing.JLabel jLwhatCheck;
    private javax.swing.JLabel jLwhatSell;
    private javax.swing.JPanel jPbuy;
    private javax.swing.JPanel jPcheck;
    private javax.swing.JPanel jPsell;
    private javax.swing.JTabbedPane jTBmain;
    private javax.swing.JTextField jTFamountBuy;
    private javax.swing.JTextField jTFamountSell;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
